version: '2'
services:
  mysql:
    container_name: mysql
    image: mysql:5.6.32
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: hogehoge
    hostname: mysql
  rails:
    container_name: rails
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - mysql
  nginx:
    container_name: nginx
    build: containers/nginx
    ports:
      - '80:80'
    depends_on:
      - rails
    volumes:
      - ./containers_data/nginx:/var/log/nginx
